import type { Metadata } from "next";
import "./globals.css";
import "./main.css";
import { roboto } from "./fonts";

export const metadata: Metadata = {
  title: "RVD Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
